<?php

/**
 * @file
 * This is the primary module file.
 */

/**
 * Implements hook_page_attachments().
 */
function meta_pixel_page_attachments(array &$attachments): void {
  $script = "!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init', '1775212186705743');fbq('track', 'PageView');";
  $noscript = '<img height="1" width="1" src="https://www.facebook.com/tr?id=1775212186705743&ev=PageView&noscript=1"/>';

  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#attributes' => [
        'type' => 'text/javascript',
      ],
      '#value' => $script,
    ],
    'bnt_meta_pixel_script',
  ];
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'noscript',
      '#value' => $noscript,
    ],
    'bnt_meta_pixel_noscript',
  ];
}
