name: 'Testing config import module'
type: module
description: 'Tests install profiles in the config importer.'
# version: VERSION
package: Testing

# Information added by Drupal.org packaging script on 2024-10-03
version: '10.3.6'
project: 'drupal'
datestamp: 1727949002
